# Generated by Django 6.0.3 on 2026-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
            ],
        ),
    ]
