# Generated by Django 6.0.3 on 2026-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider_app', '0005_driver_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
